# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MiYe_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1183, 600)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bookman Old Style"))
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 20, 531, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Zapfino"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(600, 140, 571, 351))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Screen Shot 2015-11-16 at 3.57.20 PM.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-40, 150, 641, 331))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/miye.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 100, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(510, 100, 118, 24))
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuWelcome = QtGui.QMenu(self.menubar)
        self.menuWelcome.setObjectName(_fromUtf8("menuWelcome"))
        self.menuBath = QtGui.QMenu(self.menubar)
        self.menuBath.setObjectName(_fromUtf8("menuBath"))
        self.menuMineral = QtGui.QMenu(self.menuBath)
        self.menuMineral.setObjectName(_fromUtf8("menuMineral"))
        self.menuMassage = QtGui.QMenu(self.menubar)
        self.menuMassage.setObjectName(_fromUtf8("menuMassage"))
        self.menuSweedish = QtGui.QMenu(self.menuMassage)
        self.menuSweedish.setObjectName(_fromUtf8("menuSweedish"))
        self.menuShiatsu = QtGui.QMenu(self.menuMassage)
        self.menuShiatsu.setObjectName(_fromUtf8("menuShiatsu"))
        self.menuDeep_Tissue = QtGui.QMenu(self.menuMassage)
        self.menuDeep_Tissue.setObjectName(_fromUtf8("menuDeep_Tissue"))
        self.menuFacials = QtGui.QMenu(self.menubar)
        self.menuFacials.setObjectName(_fromUtf8("menuFacials"))
        self.menuNormal = QtGui.QMenu(self.menuFacials)
        self.menuNormal.setObjectName(_fromUtf8("menuNormal"))
        self.menuCollagen = QtGui.QMenu(self.menuFacials)
        self.menuCollagen.setObjectName(_fromUtf8("menuCollagen"))
        self.menuSpecials = QtGui.QMenu(self.menubar)
        self.menuSpecials.setObjectName(_fromUtf8("menuSpecials"))
        self.menuHot_Stone = QtGui.QMenu(self.menuSpecials)
        self.menuHot_Stone.setObjectName(_fromUtf8("menuHot_Stone"))
        self.menuSugar_Scrub = QtGui.QMenu(self.menuSpecials)
        self.menuSugar_Scrub.setObjectName(_fromUtf8("menuSugar_Scrub"))
        self.menuHerbal_Body_Wrap = QtGui.QMenu(self.menuSpecials)
        self.menuHerbal_Body_Wrap.setObjectName(_fromUtf8("menuHerbal_Body_Wrap"))
        self.menuBotanical_Mud_Wrap = QtGui.QMenu(self.menuSpecials)
        self.menuBotanical_Mud_Wrap.setObjectName(_fromUtf8("menuBotanical_Mud_Wrap"))
        self.menuMembership = QtGui.QMenu(self.menubar)
        self.menuMembership.setObjectName(_fromUtf8("menuMembership"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action60_minutes = QtGui.QAction(MainWindow)
        self.action60_minutes.setObjectName(_fromUtf8("action60_minutes"))
        self.action90_minutes = QtGui.QAction(MainWindow)
        self.action90_minutes.setObjectName(_fromUtf8("action90_minutes"))
        self.action30_minutes = QtGui.QAction(MainWindow)
        self.action30_minutes.setObjectName(_fromUtf8("action30_minutes"))
        self.action60_minutes_2 = QtGui.QAction(MainWindow)
        self.action60_minutes_2.setObjectName(_fromUtf8("action60_minutes_2"))
        self.action30_minutes_2 = QtGui.QAction(MainWindow)
        self.action30_minutes_2.setObjectName(_fromUtf8("action30_minutes_2"))
        self.action60_minutes_3 = QtGui.QAction(MainWindow)
        self.action60_minutes_3.setObjectName(_fromUtf8("action60_minutes_3"))
        self.action30_minutes_3 = QtGui.QAction(MainWindow)
        self.action30_minutes_3.setObjectName(_fromUtf8("action30_minutes_3"))
        self.action60_minutes_4 = QtGui.QAction(MainWindow)
        self.action60_minutes_4.setObjectName(_fromUtf8("action60_minutes_4"))
        self.action30_minutes_4 = QtGui.QAction(MainWindow)
        self.action30_minutes_4.setObjectName(_fromUtf8("action30_minutes_4"))
        self.action60_minutes_5 = QtGui.QAction(MainWindow)
        self.action60_minutes_5.setObjectName(_fromUtf8("action60_minutes_5"))
        self.action30_minutes_5 = QtGui.QAction(MainWindow)
        self.action30_minutes_5.setObjectName(_fromUtf8("action30_minutes_5"))
        self.action60_minutes_6 = QtGui.QAction(MainWindow)
        self.action60_minutes_6.setObjectName(_fromUtf8("action60_minutes_6"))
        self.action60_minutes_7 = QtGui.QAction(MainWindow)
        self.action60_minutes_7.setObjectName(_fromUtf8("action60_minutes_7"))
        self.action90_minutes_2 = QtGui.QAction(MainWindow)
        self.action90_minutes_2.setObjectName(_fromUtf8("action90_minutes_2"))
        self.action60_minutes_8 = QtGui.QAction(MainWindow)
        self.action60_minutes_8.setObjectName(_fromUtf8("action60_minutes_8"))
        self.action90_minutes_3 = QtGui.QAction(MainWindow)
        self.action90_minutes_3.setObjectName(_fromUtf8("action90_minutes_3"))
        self.action60_minutes_9 = QtGui.QAction(MainWindow)
        self.action60_minutes_9.setObjectName(_fromUtf8("action60_minutes_9"))
        self.action90_minutes_4 = QtGui.QAction(MainWindow)
        self.action90_minutes_4.setObjectName(_fromUtf8("action90_minutes_4"))
        self.action60_minutes_10 = QtGui.QAction(MainWindow)
        self.action60_minutes_10.setObjectName(_fromUtf8("action60_minutes_10"))
        self.action90_minutes_5 = QtGui.QAction(MainWindow)
        self.action90_minutes_5.setObjectName(_fromUtf8("action90_minutes_5"))
        self.actionBuy_Card = QtGui.QAction(MainWindow)
        self.actionBuy_Card.setObjectName(_fromUtf8("actionBuy_Card"))
        self.actionAdd_credit = QtGui.QAction(MainWindow)
        self.actionAdd_credit.setObjectName(_fromUtf8("actionAdd_credit"))
        self.menuMineral.addAction(self.action60_minutes)
        self.menuMineral.addSeparator()
        self.menuMineral.addAction(self.action90_minutes)
        self.menuMineral.addSeparator()
        self.menuBath.addAction(self.menuMineral.menuAction())
        self.menuBath.addSeparator()
        self.menuSweedish.addAction(self.action30_minutes)
        self.menuSweedish.addSeparator()
        self.menuSweedish.addAction(self.action60_minutes_2)
        self.menuSweedish.addSeparator()
        self.menuShiatsu.addAction(self.action30_minutes_2)
        self.menuShiatsu.addSeparator()
        self.menuShiatsu.addAction(self.action60_minutes_3)
        self.menuShiatsu.addSeparator()
        self.menuDeep_Tissue.addAction(self.action30_minutes_3)
        self.menuDeep_Tissue.addSeparator()
        self.menuDeep_Tissue.addAction(self.action60_minutes_4)
        self.menuDeep_Tissue.addSeparator()
        self.menuMassage.addAction(self.menuSweedish.menuAction())
        self.menuMassage.addSeparator()
        self.menuMassage.addAction(self.menuShiatsu.menuAction())
        self.menuMassage.addSeparator()
        self.menuMassage.addAction(self.menuDeep_Tissue.menuAction())
        self.menuMassage.addSeparator()
        self.menuNormal.addAction(self.action30_minutes_4)
        self.menuNormal.addSeparator()
        self.menuNormal.addAction(self.action60_minutes_5)
        self.menuNormal.addSeparator()
        self.menuCollagen.addAction(self.action30_minutes_5)
        self.menuCollagen.addSeparator()
        self.menuCollagen.addAction(self.action60_minutes_6)
        self.menuCollagen.addSeparator()
        self.menuFacials.addAction(self.menuNormal.menuAction())
        self.menuFacials.addSeparator()
        self.menuFacials.addAction(self.menuCollagen.menuAction())
        self.menuFacials.addSeparator()
        self.menuHot_Stone.addAction(self.action60_minutes_7)
        self.menuHot_Stone.addSeparator()
        self.menuHot_Stone.addAction(self.action90_minutes_2)
        self.menuHot_Stone.addSeparator()
        self.menuSugar_Scrub.addAction(self.action60_minutes_8)
        self.menuSugar_Scrub.addSeparator()
        self.menuSugar_Scrub.addAction(self.action90_minutes_3)
        self.menuSugar_Scrub.addSeparator()
        self.menuHerbal_Body_Wrap.addAction(self.action60_minutes_9)
        self.menuHerbal_Body_Wrap.addSeparator()
        self.menuHerbal_Body_Wrap.addAction(self.action90_minutes_4)
        self.menuHerbal_Body_Wrap.addSeparator()
        self.menuBotanical_Mud_Wrap.addAction(self.action60_minutes_10)
        self.menuBotanical_Mud_Wrap.addSeparator()
        self.menuBotanical_Mud_Wrap.addAction(self.action90_minutes_5)
        self.menuBotanical_Mud_Wrap.addSeparator()
        self.menuSpecials.addAction(self.menuHot_Stone.menuAction())
        self.menuSpecials.addSeparator()
        self.menuSpecials.addAction(self.menuSugar_Scrub.menuAction())
        self.menuSpecials.addSeparator()
        self.menuSpecials.addAction(self.menuHerbal_Body_Wrap.menuAction())
        self.menuSpecials.addSeparator()
        self.menuSpecials.addAction(self.menuBotanical_Mud_Wrap.menuAction())
        self.menuSpecials.addSeparator()
        self.menuMembership.addAction(self.actionBuy_Card)
        self.menuMembership.addSeparator()
        self.menuMembership.addAction(self.actionAdd_credit)
        self.menuMembership.addSeparator()
        self.menubar.addAction(self.menuWelcome.menuAction())
        self.menubar.addAction(self.menuBath.menuAction())
        self.menubar.addAction(self.menuMassage.menuAction())
        self.menubar.addAction(self.menuFacials.menuAction())
        self.menubar.addAction(self.menuSpecials.menuAction())
        self.menubar.addAction(self.menuMembership.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Welcome to Mud in Your Eye Spa!", None))
        self.label_4.setText(_translate("MainWindow", "Reservation", None))
        self.menuWelcome.setTitle(_translate("MainWindow", "Welcome", None))
        self.menuBath.setTitle(_translate("MainWindow", "Bath", None))
        self.menuMineral.setTitle(_translate("MainWindow", "Mineral ", None))
        self.menuMassage.setTitle(_translate("MainWindow", "Massage", None))
        self.menuSweedish.setTitle(_translate("MainWindow", "Sweedish", None))
        self.menuShiatsu.setTitle(_translate("MainWindow", "Shiatsu", None))
        self.menuDeep_Tissue.setTitle(_translate("MainWindow", "Deep Tissue", None))
        self.menuFacials.setTitle(_translate("MainWindow", "Facials", None))
        self.menuNormal.setTitle(_translate("MainWindow", "Normal", None))
        self.menuCollagen.setTitle(_translate("MainWindow", "Collagen", None))
        self.menuSpecials.setTitle(_translate("MainWindow", "Specials", None))
        self.menuHot_Stone.setTitle(_translate("MainWindow", "Hot Stone", None))
        self.menuSugar_Scrub.setTitle(_translate("MainWindow", "Sugar Scrub", None))
        self.menuHerbal_Body_Wrap.setTitle(_translate("MainWindow", "Herbal Body Wrap", None))
        self.menuBotanical_Mud_Wrap.setTitle(_translate("MainWindow", "Botanical Mud Wrap", None))
        self.menuMembership.setTitle(_translate("MainWindow", "Gift Cards", None))
        self.action60_minutes.setText(_translate("MainWindow", "60 minutes", None))
        self.action90_minutes.setText(_translate("MainWindow", "90 minutes", None))
        self.action30_minutes.setText(_translate("MainWindow", "30 minutes", None))
        self.action60_minutes_2.setText(_translate("MainWindow", "60 minutes", None))
        self.action30_minutes_2.setText(_translate("MainWindow", "30 minutes", None))
        self.action60_minutes_3.setText(_translate("MainWindow", "60 minutes", None))
        self.action30_minutes_3.setText(_translate("MainWindow", "30 minutes", None))
        self.action60_minutes_4.setText(_translate("MainWindow", "60 minutes", None))
        self.action30_minutes_4.setText(_translate("MainWindow", "30 minutes", None))
        self.action60_minutes_5.setText(_translate("MainWindow", "60 minutes", None))
        self.action30_minutes_5.setText(_translate("MainWindow", "30 minutes", None))
        self.action60_minutes_6.setText(_translate("MainWindow", "60 minutes", None))
        self.action60_minutes_7.setText(_translate("MainWindow", "60 minutes", None))
        self.action90_minutes_2.setText(_translate("MainWindow", "90 minutes", None))
        self.action60_minutes_8.setText(_translate("MainWindow", "60 minutes", None))
        self.action90_minutes_3.setText(_translate("MainWindow", "90 minutes", None))
        self.action60_minutes_9.setText(_translate("MainWindow", "60 minutes", None))
        self.action90_minutes_4.setText(_translate("MainWindow", "90 minutes", None))
        self.action60_minutes_10.setText(_translate("MainWindow", "60 minutes", None))
        self.action90_minutes_5.setText(_translate("MainWindow", "90 minutes", None))
        self.actionBuy_Card.setText(_translate("MainWindow", "Buy Card", None))
        self.actionAdd_credit.setText(_translate("MainWindow", "Add credit", None))

import tryPic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
